BankXPath = {
    "bank_input": "//vcb-select[@formcontrolname='beneBank']//input",
    "bank_scroll": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport",
    "mbbank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='MB - Ngân hàng Quân Đội']",
    "techcombank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='TECHCOMBANK - Ngân hàng Kỹ thương Việt Nam']",
    "bidv": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='BIDV - Ngân hàng TMCP Đầu tư và Phát triển Việt Nam']",
    "vpbank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='VPBANK - Ngân hàng Việt Nam Thịnh Vượng']",
    "vietinbank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='VIETINBANK - Ngân hàng TMCP Công Thương Việt Nam']",
    "vietcombank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='Vietcombank - Ngân hàng TMCP Ngoại Thương Việt Nam']",
    "acb": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='ACB - Ngân hàng Á Châu']",
    "tpbank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='TPBANK - Ngân hàng Tiên phong']",
    "sacombank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='Sacombank - Ngân hàng thương mại cổ phần Sài gòn Thương tín']",
    "ocb": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='OCB - Ngân hàng Phương Đông']",
    "bvbank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='BVBank - Ngân hàng Bản Việt']",
    "agribank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='AGRIBANK - Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam']",
    "bvbank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='BVBank - Ngân hàng Bản Việt']",
    "bvbank": "//div[@class='cdk-overlay-container']//cdk-virtual-scroll-viewport//nz-option-item[@title='BVBank - Ngân hàng Bản Việt']",
    "account_input": "//vcb-input[@formcontrolname='beneAccount']//input",
    "name_input": "//vcb-input[@formcontrolname='beneAccountName']//input",
    "modal": "//vcb-modal-confirm",
    "modal_retry": "//vcb-modal-confirm//button//div[text()='Thử lại']"
}
